CREATE DATABASE IF NOT EXISTS shared_database
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS user_database
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS login_database
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;
